<%
DIM 	g_strCONN, g_strDBPath, g_strURL 

'g_strURL = "http://web02.zubuk.com/lss-db/"
'g_strDBPath = "C:\WORK\ascentria\ihc\DB\timesheet.mdb" '"C:\work\LSS-db\db\timesheet.mdb"
'g_strDBPath = "C:\work\LSS-db\staging\db\timesheet.mdb"
'g_strCONN = "PROVIDER=Microsoft.Jet.OLEDB.4.0;DATA SOURCE=" & g_strDBPath & ";"

g_strCONNDB = "Provider=SQLOLEDB;Data Source=ERNIE\SQLEXPRESS;Initial Catalog=timesheet;Integrated Security=SSPI;"'"Provider=SQLOLEDB;Data Source=192.168.111.25\SQLEXPRESS;Initial Catalog=langbank;User ID=testpatrick;Password=zubuk#zubuk;"
Set g_strCONN = Server.CreateObject("ADODB.Connection")
g_strCONN.Open g_strCONNDB
'g_strLangBank = "Provider=SQLOLEDB;Data Source=ERNIE\SQLEXPRESS;Initial Catalog=langbank;Integrated Security=SSPI;"

wk1 = "6/25/2006"

PayCSV 		= "C:\WORK\ascentria\ihc\export\"
RepCSV 		= "C:\WORK\ascentria\ihc\export\test.csv"
tmpdate 	= replace(date, "/", "")
ProcCSV 	= "C:\WORK\ascentria\ihc\export\ProcItem" & tmpdate & ".csv"
AdminLog 	= "C:\WORK\ascentria\ihc\export\AdminLog.txt"
UserLog 	= "C:\WORK\ascentria\ihc\export\UserLog.txt"
ConDOB 		= "C:\WORK\ascentria\ihc\export\ConsumerDOB.csv"
WorMailAdr 	= "C:\WORK\ascentria\ihc\export\WorkerMailAddress.csv"
ActiveCon 	= "C:\WORK\ascentria\ihc\export\ActiveConsumer.csv"
ActiveWor 	= "C:\WORK\ascentria\ihc\export\ActiveWorker.csv"
mipCSV 		= "C:\WORK\ascentria\ihc\export\mipImport.csv"
RepList 	=  "C:\WORK\ascentria\ihc\export\RepList.csv"
WorkerList 	=  "C:\WORK\ascentria\ihc\List\worker.txt"
RepresentList =  "C:\WORK\ascentria\ihc\List\Representative.txt"
CaseList 	=  "C:\WORK\ascentria\ihc\List\Case_Manager.txt"
BWorkerList =  "C:\WORK\ascentria\ihc\List\Bworker.txt"
ConPMTown 	= "C:\WORK\ascentria\ihc\export\ConPMTown.csv"
WorPMTown 	= "C:\WORK\ascentria\ihc\export\WorPMTown.csv"
CaseListCSV = "C:\WORK\ascentria\ihc\export\CaseListCSV.csv"
MileageCSV 	= "C:\WORK\ascentria\ihc\export\MileageCSV.csv"
prfjdepiCSV = "C:\WORK\ascentria\ihc\export\prfjdepi.csv"
PPCSV 		= "C:\WORK\ascentria\ihc\export\WorkerPPCSV.csv"
PPdteCSV 	= "C:\WORK\ascentria\ihc\export\PPdteCSV.csv"
THrsCSV 	= "C:\WORK\ascentria\ihc\export\THrsCSV.csv"
SimProcCSV 	= "C:\WORK\ascentria\ihc\export\SimProcCSV.csv" 
NewsCSV 	= "C:\WORK\ascentria\ihc\export\NewsCSV.csv" 
uploadpath 	= "C:\WORK\ascentria\ihc\import\"
BackupDest 	= "C:\WORK\ascentria\ihc\BackupCSV\"
MedCSV 		= "C:\WORK\ascentria\ihc\export\consumermedicaid.csv" 
BackupDest 	= "C:\WORK\ascentria\ihc\BackupCSV\"
copyfile 	= "C:\WORK\ascentria\ihc\csv\"
copyfile2 	= "csv/"
uploadFilePath = "C:\WORK\ascentria\ihc\upload\"
ActiveConCase = "C:\WORK\ascentria\ihc\export\ActiveConCase.csv"
strtinactivedte = "C:\WORK\ascentria\ihc\export\StartandInactiveCon.csv"
conpcsp 	= "C:\WORK\ascentria\ihc\export\ConPCSP.csv"
lcsExp 		= "C:\WORK\ascentria\ihc\export\lcsExp.csv"
InsExp 		= "C:\WORK\ascentria\ihc\export\InsExp.csv"
tbtest 		= "C:\WORK\ascentria\ihc\export\tbtest.csv"
ppay 		= "C:\WORK\ascentria\ihc\export\ppay.csv"
svcon 		= "C:\WORK\ascentria\ihc\export\svcon.csv"
svwor 		= "C:\WORK\ascentria\ihc\export\svwor.csv"
ouputPath 	= "C:\WORK\ascentria\ihc\output\"
insuf 		= "C:\WORK\ascentria\ihc\export\insuf.csv"
dteofhire 	= "C:\WORK\ascentria\ihc\export\dteofhire.csv"
wdriver 	= "C:\WORK\ascentria\ihc\export\wdriver.csv"
wcom 		= "C:\WORK\ascentria\ihc\export\wcom.csv"
%>